### ISSUE TITLE
ValueError: Unable to configure formatter 'access' (Py 3.8)

### ISSUE THREAD

**Issue by aamalev** [aioworkers/aioworkers-aiohttp#44]
```
logging:
  version: 1
  formatters:
    access:
      format: %a %t "%r" %s %b "%{Referer}i" "%{User-Agent}i"
```
